### ISSUE TITLE
Exported Layer doesn't color based on score and Layer Title ignored

### ISSUE THREAD

**Issue by clr2of8** [center-for-threat-informed-defense/attack-powered-suit#12]
I exported a layer with these settings

![image](https://user-images.githubusercontent.com/22311332/181864855-159afb8c-3e5b-406a-a25d-2cb43aef3267.png)

The custom Layer Title I used was ignored and since I didn't specify a layer color I would expect the cells to be colored based on their score and the default color gradient.

**Comment by mehaase** [comment]
Hi, thank you for reporting these issues! Just wanted to acknowledge that we've seen them and will work on getting them fixed.
