### ISSUE TITLE
Removed Bookmarks are still exported to layer

### ISSUE THREAD

**Issue by clr2of8** [center-for-threat-informed-defense/attack-powered-suit#13]
I used to have a bookmark for T1547.001 and T1012 on this list, but I clicked the green bookmark next to them to remove them.

![image](https://user-images.githubusercontent.com/22311332/181865447-86b56292-aae6-4f82-8ce4-d01ad9a8389d.png)

Now T1547.001 and T1012 are not on the list but when I export, they are still in my layer.

![image](https://user-images.githubusercontent.com/22311332/181865467-ef13d164-e5bc-46bc-9c7b-07ca208709f2.png)

**Comment by mehaase** [comment]
This was also fixed in #23.
