### ISSUE TITLE
Exporting software to a layer doesn't select associated techniques on the layer in the Navigator

### ISSUE THREAD

**Issue by clr2of8** [center-for-threat-informed-defense/attack-powered-suit#14]
If I search "mimikatz" in the Navigator, it selects all the techniques that use that software.

![image](https://user-images.githubusercontent.com/22311332/181865705-3f054db6-2c88-4ac1-a78f-c2e35d04bb0a.png)

But exporting software bookmarks to a layer doesn't do anything to the visual layer in navigator, so isn't a useful option as is.

![image](https://user-images.githubusercontent.com/22311332/181865766-51286d41-2c4e-4436-9447-e2f6c6932fdc.png)

**Comment by mehaase** [comment]
I modified the export feature to behave as expected. E.g. if you have mimikatz bookmarked:

![Screen Shot 2022-12-29 at 3 13 07 PM](https://user-images.githubusercontent.com/320904/210007033-49a58f6d-addc-4aa1-a7a4-978ce57d74ec.png)

Then it exports all of the techniques related to Mimikatz (as defined by the STIX relationships in our source data):

![Screen Shot 2022-12-29 at 3 13 35 PM](https://user-images.githubusercontent.com/320904/210007027-ddebfb91-8308-4829-a417-3bf8bc05a952.png)

Colors/scores and notes are copied over from the bookmark to the related techniques.
