### ISSUE TITLE
Missing search results for procdump

### ISSUE THREAD

**Issue by clr2of8** [center-for-threat-informed-defense/attack-powered-suit#16]
When I search for procdump on the mitre site I get results

![image](https://user-images.githubusercontent.com/22311332/182699572-80413e14-5169-43b7-b3f1-7ab7f00792fd.png)

But I don't when searching with the extension

![image](https://user-images.githubusercontent.com/22311332/182699647-efb31385-a568-44a8-a692-7e0b588fb72d.png)

**Comment by clr2of8** [comment]
I also see missing search results in the search for `Base64` as shown in the image below:
![image](https://user-images.githubusercontent.com/22311332/204112859-58d5ef2a-d5a2-49c5-9ae5-b9aacf9e0d2a.png)

**Comment by mehaase** [comment]
I'm taking a look at this today. The text search library (fuse.js) has a limited match distance, so if keywords are more than 1000 characters into the description, it seems that fuse.js will not find them. I tried increasing the fuse distance to 10,000 to confirm this.

While increasing the distance does improve the situation a bit, I think fuse.js is a deadend for this project. The better solution would be to replace fuse.js with something more appropriate for our needs (see #4).

**Comment by mehaase** [comment]
This should be fixed in #28 and will be included in 1.2.0 release in the next couple weeks.

**Comment by mehaase** [comment]
Some screenshots to show how the new search engine handles the problematic queries posted by @clr2of8:

<img width="807" alt="Screen Shot 2022-12-20 at 3 03 08 PM" src="https://user-images.githubusercontent.com/320904/208756270-d5223475-53a3-4ad5-9753-e177384ad5e2.png">

<img width="785" alt="Screen Shot 2022-12-20 at 3 03 24 PM" src="https://user-images.githubusercontent.com/320904/208756268-f2c3d431-9583-484e-abc1-ccf1e9a264cb.png">
