### ISSUE TITLE
some matrix values are incorrect or incomplete

### ISSUE THREAD

**Issue by jakewarren** [center-for-threat-informed-defense/attack-powered-suit#21]
**Describe the bug**
I discovered a limitation in the implementation of #20, for some items the matrix value in the `external_references` field of the STIX data is incorrect (or I am misunderstanding its intended use). For example T1521.002 belongs to the Mobile matrix but the reference's `source_name` is "mitre-attack" (Enterprise) instead of "mitre-mobile-attack" (Mobile). 

```json
"external_references": [
        {
          "source_name": "mitre-attack",
          "external_id": "T1521.002",
          "url": "https://attack.mitre.org/techniques/T1521/002"
        }
      ],
```

So I then switched the code to utilize the `x_mitre_domains` value which seems to be accurate as far as I can tell. But that introduces another issue because some items like G0088 have multiple matrices assigned to them which impacts both display and filtering functionality. 
```json
 "x_mitre_domains": [
        "enterprise-attack",
        "ics-attack"
      ],
```
  <details>
   <summary>List of items with multiple matrices assigned</summary>

  ```sh
Reading data/enterprise-attack.json… warning: object M1013 has more than one matrix listed in 'x_mitre_domains'
warning: object S0182 has more than one matrix listed in 'x_mitre_domains'
done
Reading data/ics-attack.json… warning: object G0035 has more than one matrix listed in 'x_mitre_domains'
warning: object G0034 has more than one matrix listed in 'x_mitre_domains'
warning: object G0049 has more than one matrix listed in 'x_mitre_domains'
warning: object G0074 has more than one matrix listed in 'x_mitre_domains'
warning: object G0088 has more than one matrix listed in 'x_mitre_domains'
warning: object G0032 has more than one matrix listed in 'x_mitre_domains'
warning: object G0064 has more than one matrix listed in 'x_mitre_domains'
warning: object S0605 has more than one matrix listed in 'x_mitre_domains'
warning: object S0093 has more than one matrix listed in 'x_mitre_domains'
warning: object S0603 has more than one matrix listed in 'x_mitre_domains'
warning: object S0606 has more than one matrix listed in 'x_mitre_domains'
warning: object S0089 has more than one matrix listed in 'x_mitre_domains'
warning: object S0368 has more than one matrix listed in 'x_mitre_domains'
warning: object S0608 has more than one matrix listed in 'x_mitre_domains'
warning: object S0372 has more than one matrix listed in 'x_mitre_domains'
warning: object S0038 has more than one matrix listed in 'x_mitre_domains'
warning: object S0366 has more than one matrix listed in 'x_mitre_domains'
warning: object S0446 has more than one matrix listed in 'x_mitre_domains'
warning: object S0496 has more than one matrix listed in 'x_mitre_domains'
warning: object S0607 has more than one matrix listed in 'x_mitre_domains'
warning: object S0604 has more than one matrix listed in 'x_mitre_domains'
warning: object S0143 has more than one matrix listed in 'x_mitre_domains'
warning: object DS0002 has more than one matrix listed in 'x_mitre_domains'
warning: object DS0024 has more than one matrix listed in 'x_mitre_domains'
warning: object DS0012 has more than one matrix listed in 'x_mitre_domains'
warning: object DS0015 has more than one matrix listed in 'x_mitre_domains'
warning: object DS0028 has more than one matrix listed in 'x_mitre_domains'
warning: object DS0022 has more than one matrix listed in 'x_mitre_domains'
warning: object DS0016 has more than one matrix listed in 'x_mitre_domains'
warning: object DS0017 has more than one matrix listed in 'x_mitre_domains'
warning: object DS0033 has more than one matrix listed in 'x_mitre_domains'
warning: object DS0029 has more than one matrix listed in 'x_mitre_domains'
warning: object DS0003 has more than one matrix listed in 'x_mitre_domains'
warning: object DS0001 has more than one matrix listed in 'x_mitre_domains'
warning: object DS0019 has more than one matrix listed in 'x_mitre_domains'
warning: object DS0009 has more than one matrix listed in 'x_mitre_domains'
warning: object DS0011 has more than one matrix listed in 'x_mitre_domains'
warning: object M1013 has more than one matrix listed in 'x_mitre_domains'
done
Reading data/mobile-attack.json… warning: object M1013 has more than one matrix listed in 'x_mitre_domains'
warning: object S0182 has more than one matrix listed in 'x_mitre_domains'
  ```
  </details>

> If you want to express positive or negative feedback on a bug report, please leave a Thumbs Up or Thumbs Down so that we can keep track of demand. Please do not reply just to say +1 or -1. Thanks!

**Comment by mehaase** [comment]
Thank you for finding this and researching it in such depth! The `x_mitre_domains` property seems like the best bet. On the display side, is there any reason we can't show a label for each matrix?

<img width="805" alt="search result containing both enterprise and ics tag" src="https://user-images.githubusercontent.com/320904/189129602-275f751a-9fd4-40a7-94d4-410778307b45.png">

It might get cluttered but it seems straightforward.

On the filtering side, the `attackObject.source_name` variable will need to be split up into 3 new boolean variables, e.g. `attackObject.is_enterprise`, `attackObject.is_mobile`, and `attackObject.is_ics`.

Does this approach make sense? AmI missing any key aspects of the problem?

**Comment by jondricek** [comment]
Hey, so I'd love to step in real quick and give some ATT&CK STIX background on this. ATT&CK is represented in both [STIX 2.0](https://github.com/mitre/cti) and [STIX 2.1](https://github.com/mitre-attack/attack-stix-data). The `x_mitre_domains` STIX extension field was initially added only to the STIX 2.1 content, but we added it to STIX 2.0 in the v11 release earlier this year in April 2022 as well. 

Historically the `external_references[0].source_name` field has been `mitre-attack` (Enterprise), `mitre-mobile-attack` (Mobile), etc. but starting this October for the v12 release that will be `mitre-attack` for all domains, and the `x_mitre_domains` string[] field will be used in its place since we expect there to be objects that can span multiple domains. 

Since you are not going to be the only downstream project effected by this I will be writing up a "What is changing in MITRE ATT&CK STIX with v12 and how it can impact you - for developers" in the next week or so and it will likely be broadcast via the Twitter account when its ready so people will know how to brace for any impact.

For reference, this pull request conversation has some additional insights https://github.com/mitre/cti/pull/196

**Comment by mehaase** [comment]
I received an email asking about this today and it includes a reproduction case:

![image](https://user-images.githubusercontent.com/320904/192794173-bede319f-33a1-4e18-9408-853e0a992123.png)

It shows T1420 mistakenly tagged as Enterprise instead of Mobile, and showing up in results even though the Mobile switch is off.

**Comment by jakewarren** [comment]
> I received an email asking about this today and it includes a reproduction case

I am polishing up a PR to fix this, just tested and looks like my changes do resolve that use case. 

<img width="581" alt="ATT CK 2022-09-28 09-00-46" src="https://user-images.githubusercontent.com/6472686/192799523-1c8e4f33-acd3-486e-ade3-34a71f660504.png">

While implementing the PR to fix this issue I ran across a related but out of scope issue, I will document that in the 'Limitations' section of the PR.

**Comment by mehaase** [comment]
@jakewarren Thanks for the PR -- I reviewed and merged it this morning. As for release timing, we are planning to fix a few of the other open issues and do a release in 2-3 weeks. Does that timing work for you or would you like to get this patch rolled out sooner? I'm happy to do a release if you need it.

**Comment by jakewarren** [comment]
@mehaase that timing works for me, thanks!
