### ISSUE TITLE
Uncheck All/Check All Button for ATT&CK Power Suit Page

### ISSUE THREAD

**Issue by rmasuoka** [center-for-threat-informed-defense/attack-powered-suit#31]
I would like to see "Uncheck All" and "Check All" Buttons (or toggle switch)  for ATT&CK Power Suit Page.
It will unselect or select all the types of objects (except Deprecated) to include in search results. 
I realized it would be a nice-to-have feature when I tried to select only Techniques.

**Comment by mehaase** [comment]
Great idea; I'll work this into the next release.

**Comment by rmasuoka** [comment]
Cool & thanks!
