### ISSUE TITLE
Search filtering restricts results too much

### ISSUE THREAD

**Issue by Cuteness-overload** [center-for-threat-informed-defense/attack-powered-suit#39]
**Describe the bug**

When doing a search for different objects in the ATT&CK extension, the filter requires all of an object's types to be active before that object appears in the results.
For instance, if we search "Panda" with the "Enterprise" and "Group" filters on, we can see various groups in the results.
![image](https://user-images.githubusercontent.com/91355119/230728984-4e911087-32c5-4fee-b4ee-183fb46ed62c.png)

But if either one of those filters are switched off, we do not get any results, even though the objects clearly have both tags.
![image](https://user-images.githubusercontent.com/91355119/230729036-66cbd4b2-c5ad-4d8f-8dae-bf2dbf6458ae.png)
![image](https://user-images.githubusercontent.com/91355119/230729534-b406aa80-a391-4545-b698-60e33423c686.png)

Another example of this behaviour would be when searching for "phishing". A lot of results have the "Enterprise" and "Techniques" type assigned to them. If either "enterprise" or "techniques" are turned off in the filters, there will be no results shown.

***If this is expected behaviour, implementing the option to have a less restrictive filter might be a good idea.***

---

**To Reproduce**

Provide detailed steps to reproduce this outcome.

1. Select type of objects you want to filter in extension
2. If a result has other types assigned to it (besides the selected ones), they will not show up.

**Platform:**
 - OS: Windows
 - Browser: Firefox
 - Browser Version: 111.0.1 (64-bit)

> If you want to express positive or negative feedback on a bug report, please leave a Thumbs Up or Thumbs Down so that we can keep track of demand. Please do not reply just to say +1 or -1. Thanks!

**Comment by mehaase** [comment]
This is the expected behavior: the filters are AND conditions. For example, if a user is working on an enterprise security project, they can set up their filters to only see Enterprise results. I think this makes sense for the default behavior.

There is an extended search syntax (similar to Solr / Lucene syntax) to search by object type, domain, etc., and those are OR conditions:

![Screenshot 2023-04-10 at 9 52 31 AM](https://user-images.githubusercontent.com/320904/230914707-b5c0bf8d-afb5-412f-88ca-d042e9ef793e.png)

If you scroll down a bit from that search, you'll see some results that are Group but not ICS.

![Screenshot 2023-04-10 at 9 55 06 AM](https://user-images.githubusercontent.com/320904/230915201-f5858ec6-adf9-4919-b393-1fa58c4482a2.png)

**Comment by Cuteness-overload** [comment]
I may be misunderstanding, but if the filters are AND conditions, wouldn't selecting all of them (as is default) block any results from showing?
The current behaviour seems to be ***(Enterprise OR ICS OR mobile) AND (other option OR other options OR etc)*** as highlighted by the below screenshot
![image](https://user-images.githubusercontent.com/91355119/230975629-8d0be2f1-6f4e-4523-a9b3-87059b5f28e7.png)

Since there seems to be a distinction made between the enterprise/ICS/mobile filters and the rest of the filter types, would highlighting this difference (maybe through a visual separator) be a possible idea?
![image](https://user-images.githubusercontent.com/91355119/230978430-5b0dc602-d53f-46b5-a936-afad7e4cffec.png)

**Comment by mehaase** [comment]
> The current behaviour seems to be (Enterprise OR ICS OR mobile) AND (other option OR other options OR etc) as highlighted by the below screenshot

Yes -- this is correct (I oversimplified in my previous reply)

> would highlighting this difference (maybe through a visual separator) be a possible idea?

Yes, this is a good idea! We will work this into an upcoming release.

**Comment by mehaase** [comment]
I fixed this in #50. This is what it looks like:

<img width="601" alt="Screenshot 2024-02-12 at 3 20 34 PM" src="https://github.com/center-for-threat-informed-defense/attack-powered-suit/assets/320904/0c5fd9f6-4d84-4255-9332-232d8d6e9c5f">
