### ISSUE TITLE
Use a better text search library

### ISSUE THREAD

**Issue by mehaase** [center-for-threat-informed-defense/attack-powered-suit#4]
In the 1.0.1 release we are using [fuse.js](https://fusejs.io/), which uses a "fuzzy search" that leads to undesired results in some cases:

<img width="601" alt="screenshot of undesired search results" src="https://user-images.githubusercontent.com/320904/175566283-c2993e7a-a9e7-42d4-b368-1bf3ed15db8d.png">

In this screenshot, a search for "evasion" also matches the "avoi" in "avoid" and the "enses" in "defenses". This is not useful.

A few requirements for a replacement library:

- Inverse index for text search
- Tokenization and stemming
- Serialize / unserialize index
- Highlighting
- Multi-field index (ID, name, and description)
- Boosting ID and name
- Simple query syntax for end users

Nice to have:

- Spell correction / did you mean?
- Synonyms / semantic search

> If you want to express positive or negative feedback on a bug report, please leave a Thumbs Up or Thumbs Down so that we can keep track of demand. Please do not reply just to say +1 or -1. Thanks!

**Comment by Cyb3r-Monk** [comment]
When I search for "DLLs" the Regsvr32 is not listed in the results. 
<img width="593" alt="image" src="https://user-images.githubusercontent.com/26627224/176854168-3b2fd7b6-60dd-48bc-95ad-35c2059960b0.png">

**Comment by mehaase** [comment]
Look at 3 libraries:

## [lunr.js](https://github.com/olivernn/lunr.js)

Pros:

* The oldest and most mature of the three.
* Meets all the requirements.

Cons:

* Not very actively maintained. Last commit Aug 2020.

## [Lyra](https://github.com/LyraSearch/lyra)

Pros:

* Actively maintained with lots of planned future development.
* Supported by a \[small\] commercial entity.
* Meets all requirements except highlighting is still experimental.

Cons:

* Highlighting support was just added recently and is not documented; it may not even be fully baked.

## [ndx](https://github.com/ndx-search/ndx)

Pros:

* None

Cons:

* Not actively maintained.
* Does not meet all requirements: no highlighting.
* Not great documentation.

## [ElasticLunr](https://github.com/weixsong/elasticlunr.js/)

Pros:

* Based on lunr.js and seems to meet all the requirements.

Cons:

* The creator does not maintain it anymore. Last commit Oct 2019.
* Not great documentation.

**Comment by mehaase** [comment]
I built a prototype using Lyra but didn't get very far -- Lyra's still fairly incomplete and their build tooling doesn't work well with our rollup config.

So then I switched to Lunr.js and found that it works pretty well for our needs. Example of the same "evasion" query at the top of this thread:

<img width="792" alt="Screen Shot 2022-12-20 at 2 34 04 PM" src="https://user-images.githubusercontent.com/320904/208752211-379e5512-aa88-4537-8025-8cbb9607c285.png">

Much better result: it doesn't highlight the random characters in "avoid" and "defenses" like fuse.js does.

And here is Cybr-Monk's query (there are so many hits for "DLLs" that I also had to add "Regsvr32" to make the result appear near the top):

<img width="796" alt="Screen Shot 2022-12-20 at 2 37 26 PM" src="https://user-images.githubusercontent.com/320904/208752342-c5538b4a-d667-4966-a72d-28a62aa02e1a.png">

Here's another query that demonstrates lunr.js's stemming:

<img width="797" alt="Screen Shot 2022-12-20 at 11 13 40 AM" src="https://user-images.githubusercontent.com/320904/208752421-4ea4a71e-1636-4f12-9704-1262993cb7f7.png">

I'm satisfied with the results and will make a PR shortly.

**Comment by mehaase** [comment]
I also improved the highlighting code so that it can now excerpt from the middle of a long block of description text. (In the 1.1 release, you can end up with really long text blocks because it's trying to display the matched description starting from the beginning of the string.)

<img width="794" alt="Screen Shot 2022-12-20 at 2 55 51 PM" src="https://user-images.githubusercontent.com/320904/208755308-a8f23cf2-a53a-4bbd-bf70-f7647d515f25.png">

Notice how this example has ellipses both before and after the excerpt -- this is the middle section of a very long description.
