### ISSUE TITLE
Search popup height broken on Firefox 128

### ISSUE THREAD

**Issue by jakewarren** [center-for-threat-informed-defense/attack-powered-suit#51]
**Describe the bug**

The search panel size is broken after an update to Firefox v128, appearing with a low height value making it very difficult to use the form. The panel is still scroll-able though. If you do scroll down the panel and provide a query, the panel will expand out to normal expected size.

![ATT CK Powered Suit 2024-07-17 10-05-32](https://github.com/user-attachments/assets/9e116cc4-4190-4336-9698-bb7ca5995153)

**To Reproduce**

1. Update to 128.0 on Firefox
2. Click the extension icon to activate the search panel.
3. The search panel will pop up with a normal width value but very low height value. 

Note: I also created a brand new profile to rule out any conflicts/configuration issues. 

**Platform:**
 - OS: MacOS
 - Browser: Firefox
 - Browser Version: 128.0

> If you want to express positive or negative feedback on a bug report, please leave a Thumbs Up or Thumbs Down so that we can keep track of demand. Please do not reply just to say +1 or -1. Thanks!

**Comment by mehaase** [comment]
Thank you for reporting this, Jake. I'm seeing this on my machine too. We'll prioritize this to get fixed.
