### ISSUE TITLE
Release on UK Mac App Store

### ISSUE THREAD

**Issue by ssnkhan** [center-for-threat-informed-defense/attack-powered-suit#54]
**Describe the bug**

The App does not appear to be available for users of the UK Mac App Store.

![Screenshot 2024-10-13 at 09 47 47](https://github.com/user-attachments/assets/a1438756-d755-454d-a21a-6d70b618abef)

**To Reproduce**

Try to download the App via the UK App Store.

**Platform:**
 - OS: macOS Sequoia, 15.0.1 (24A348)
 - Browser: Safari
 - Browser Version: Version 18.0.1 (20619.1.26.31.7)

Grateful for your help, and thanks for releasing another great tool!

**Comment by mehaase** [comment]
Thanks @ssnkhan, we are still working on this; having some issues with Apple's legal department.

**Comment by ssnkhan** [comment]
@mehaase Just managed to download this successfully from the UK App Store!
