### ISSUE TITLE
Missing Software From Search results

### ISSUE THREAD

**Issue by nasbench** [center-for-threat-informed-defense/attack-powered-suit#6]
When searching for software using the extension some software doesn't show up. A couple of examples I tested so far are

- mimikatz
- nltest
- Out1
- Ping

Also some software do not show up until you type more not the initial for example "PJApps" doesn't show up until we add a third letter.

**Comment by nasbench** [comment]
Btw this also applies to some searches as well. For example when searching for "threat actor" we get results but adding an "S" will show no results. Even though there exists in the Att&ck website for example.

**Comment by mehaase** [comment]
> When searching for software using the extension some software doesn't show up.

Thank you for pointing this out with specific examples. I'll make a PR today to fix it.

> Also some software do not show up until you type more not the initial for example "PJApps" doesn't show up until we add a third letter.
> …
> Btw this also applies to some searches as well. For example when searching for "threat actor" we get results but adding an "S" will show no results. Even though there exists in the Att&ck website for example.

Some of these limitations are inherent to the fuse.js search library used inside ATT&CK Powered Suit (see #4). It is possible we could solve this with some tuning of the fuse.js settings, but it has some tradeoffs in terms of making some queries work better at the expense of other queries becoming worse. Please a comment on #4 if you have more examples of search queries that you don't think are working correctly.
